CREATE TABLE IF NOT EXISTS Post (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    indexed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    cid TEXT UNIQUE,
    uri TEXT UNIQUE,
    parameters JSONB
);

CREATE TABLE IF NOT EXISTS SubscriptionState (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    service TEXT UNIQUE,
    cursor INT
);
